server:
  port: 8082

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: user-service
  data.mongodb.uri: mongodb://localhost:27017/user